on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: Test

jobs:
  test:
    name: Test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Build Container
        run: docker build -t assassyn-dev .
      - name: Run Python Lint
        run:
          docker run --rm -v ${{ github.workspace }}:/app --user $(id -u):$(id -g) assassyn-dev pylint --rcfile python/.pylintrc python/assassyn
      - name: Python Frontend Unit Tests
        run: |
          docker run --rm -v ${{ github.workspace }}:/app --user $(id -u):$(id -g) assassyn-dev pytest -n 8 python/unit-tests